backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

site_url: "https://microbiologiachuc.github.io/manualcolheitas/"
display_url: "https://microbiologiachuc.github.io/manualcolheitas/"

publish_mode: editorial_workflow

collections:
  - name: "testes"
    label: "Testes"
    label_singular: "Teste"
    folder: "content/testes"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - label: "Nome do teste"
        name: "title"
        widget: "string"
        required: true

      - label: "Área"
        name: "area"
        widget: "select"
        options:
          - "Hematologia"
          - "Imunologia / Autoimunidade"
          - "Microbiologia"
          - "Química Clínica"
          - "Citometria de Fluxo"
          - "Farmacocinética Avançada"
        required: true

      - label: "Método"
        name: "metodo"
        widget: "string"
        required: true

      - label: "Amostra"
        name: "amostra"
        widget: "string"
        required: true

      - label: "Material de Colheita"
        name: "material_colheita"
        widget: "string"
        required: true

      - label: "Descrição clínica"
        name: "descricao_clinica"
        widget: "markdown"

      - label: "Indicação / quando solicitar"
        name: "indicacao"
        widget: "markdown"

      - label: "Transporte/Estabilidade"
        name: "transporte_estabilidade"
        widget: "markdown"

      - label: "Tempo de resposta"
        name: "tempo_resposta"
        widget: "string"
        required: true

      - label: "Setor"
        name: "setor"
        widget: "string"
        required: true

      - label: "Observações importantes"
        name: "observacoes"
        widget: "markdown"
