backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

site_url: "https://acessoeditores.netlify.app"
display_url: "https://acessoeditores.netlify.app"

publish_mode: simple

collections:
  - name: "testes"
    label: "Testes"
    label_singular: "Teste"
    folder: "content/testes"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - label: "Nome do teste"
        name: "title"
        widget: "string"

      - label: "Área"
        name: "area"
        widget: "select"
        options:
          - "Hematologia"
          - "Imunologia / Autoimunidade"
          - "Microbiologia"
          - "Química Clínica"

      - label: "Descrição clínica"
        name: "descricao_clinica"
        widget: "text"

      - label: "Indicação / quando solicitar"
        name: "indicacao"
        widget: "text"

      - label: "Tipo de amostra"
        name: "tipo_amostra"
        widget: "string"

      - label: "Método"
        name: "metodo"
        widget: "string"

      - label: "Tempo de resposta"
        name: "tempo_resposta"
        widget: "string"

      - label: "Observações importantes"
        name: "observacoes"
        widget: "text"
