backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

site_url: "https://acessoeditores.netlify.app"
display_url: "https://acessoeditores.netlify.app"

publish_mode: editorial_workflow

collections:
  - name: "items"
    label: "Itens"
    label_singular: "Item"
    folder: "items"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Imagem", name: "image", widget: "image", allow_multiple: false }
      - { label: "Categoria", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
